print("Hellow "+"World")

print("h")
print("e")
print("l")
print("l")
print("o")
print("w")

name=input("enter name")
age=input('enter age')
collage=input('enter collage name')
eng=int(input("enter marks in eng"))
nep=int(input("enter marks in nep"))
sci=int(input("enter marks in sci"))
sum=eng+nep+sci
print("name:,name")
print("age:+age")
print("collage:%"%collage)
print("the sum of the marks is",sum)
